### ISSUE TITLE
安装最新版1.15.1fore出错

### ISSUE THREAD

**Issue by daofeng2015** [Goose-Bomb/GBCLV3#20]
System.InvalidOperationException: Unable to close ViewModel GBCLV3.ViewModels.ForgeInstallViewModel as it must have a conductor as a parent (note that windows and dialogs automatically have such a parent)
   at Stylet.Screen.RequestClose(Nullable`1 dialogResult) in /_/Stylet/Screen.cs:line 316
   at GBCLV3.ViewModels.ForgeInstallViewModel.InstallSelected(Forge forge)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[Launcher Version: 3.0.7.59]

**Comment by Goose-Bomb** [comment]
看上去像是stylet框架的问题，试试最新版看还会不会这样（已经将内置的stylet升级到最新）
