### ISSUE TITLE
软件打开报错

### ISSUE THREAD

**Issue by Mrbluewu** [Goose-Bomb/GBCLV3#27]
System.NullReferenceException: Object reference not set to an instance of an object.
   at GBCLV3.Services.Launch.VersionService.Load(String jsonPath)
   at GBCLV3.Services.Launch.VersionService.<>c.<LoadAll>b__14_2(String jsonPath)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at GBCLV3.Services.Launch.VersionService.LoadAll()
   at GBCLV3.ViewModels.Windows.MainViewModel.OnInitialActivate()
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState) in /_/Stylet/Screen.cs:line 170
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler) in /_/Stylet/Screen.cs:line 155
   at Stylet.Screen.Stylet.IScreenState.Activate() in /_/Stylet/Screen.cs:line 165
   at Stylet.ScreenExtensions.TryActivate(Object screen) in /_/Stylet/ScreenExtensions.cs:line 18
   at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel) in /_/Stylet/WindowManager.cs:line 250
   at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel) in /_/Stylet/WindowManager.cs:line 224
   at Stylet.WindowManager.ShowWindow(Object viewModel, IViewAware ownerViewModel) in /_/Stylet/WindowManager.cs:line 102
   at Stylet.WindowManager.ShowWindow(Object viewModel) in /_/Stylet/WindowManager.cs:line 92
   at Stylet.BootstrapperBase.DisplayRootView(Object rootViewModel) in /_/Stylet/BootstrapperBase.cs:line 100
   at Stylet.Bootstrapper`1.Launch() in /_/Stylet/Bootstrapper.cs:line 92
   at Stylet.BootstrapperBase.Start(String[] args) in /_/Stylet/BootstrapperBase.cs:line 81
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e) in /_/Stylet/BootstrapperBase.cs:line 48
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[Launcher Version: 3.0.9.104]

**Comment by wwdwdswsdw** [comment]
Exit Code: 1
AL lib: (EE) alc_cleanup: 1 device not closedJava HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000da000000, 33554432, 0) failed; error='页面文件太小，无法完成操作。' (DOS error/errno=1455)
[Launcher Version: 3.12.150]

**Comment by Goose-Bomb** [comment]
> 页面文件太小，无法完成操作。

你的电脑内存不足，这个应该不是启动器的问题。

**Comment by happyme531** [comment]
System.NullReferenceException: Object reference not set to an instance of an object.
   at GBCLV3.Services.Launch.VersionService.Load(String jsonPath)
   at GBCLV3.Services.Launch.VersionService.<LoadAll>b__15_2(String jsonPath)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at GBCLV3.Services.Launch.VersionService.LoadAll()
   at GBCLV3.ViewModels.Windows.MainViewModel.OnInitialActivate()
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState) in /_/Stylet/Screen.cs:line 170
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler) in /_/Stylet/Screen.cs:line 155
   at Stylet.Screen.Stylet.IScreenState.Activate() in /_/Stylet/Screen.cs:line 165
   at Stylet.ScreenExtensions.TryActivate(Object screen) in /_/Stylet/ScreenExtensions.cs:line 18
   at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel) in /_/Stylet/WindowManager.cs:line 250
   at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel) in /_/Stylet/WindowManager.cs:line 224
   at Stylet.WindowManager.ShowWindow(Object viewModel, IViewAware ownerViewModel) in /_/Stylet/WindowManager.cs:line 102
   at Stylet.WindowManager.ShowWindow(Object viewModel) in /_/Stylet/WindowManager.cs:line 92
   at Stylet.BootstrapperBase.DisplayRootView(Object rootViewModel) in /_/Stylet/BootstrapperBase.cs:line 100
   at Stylet.Bootstrapper`1.Launch() in /_/Stylet/Bootstrapper.cs:line 92
   at Stylet.BootstrapperBase.Start(String[] args) in /_/Stylet/BootstrapperBase.cs:line 81
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e) in /_/Stylet/BootstrapperBase.cs:line 48
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[Launcher Version: 3.12.150]

同样的问题
电脑有26G内存可用

**Comment by Goose-Bomb** [comment]
> Load

可以提供更多信息吗？比如游戏版本？

**Comment by Goose-Bomb** [comment]
> System.NullReferenceException: Object reference not set to an instance of an object.
> at GBCLV3.Services.Launch.VersionService.Load(String jsonPath)
> at GBCLV3.Services.Launch.VersionService.b__15_2(String jsonPath)
> at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext() at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
> at GBCLV3.Services.Launch.VersionService.LoadAll()
> at GBCLV3.ViewModels.Windows.MainViewModel.OnInitialActivate()
> at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState) in /_/Stylet/Screen.cs:line 170 at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler) in /_/Stylet/Screen.cs:line 155 at Stylet.Screen.Stylet.IScreenState.Activate() in /_/Stylet/Screen.cs:line 165 at Stylet.ScreenExtensions.TryActivate(Object screen) in /_/Stylet/ScreenExtensions.cs:line 18 at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel) in /_/Stylet/WindowManager.cs:line 250 at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel) in /_/Stylet/WindowManager.cs:line 224 at Stylet.WindowManager.ShowWindow(Object viewModel, IViewAware ownerViewModel) in /_/Stylet/WindowManager.cs:line 102 at Stylet.WindowManager.ShowWindow(Object viewModel) in /_/Stylet/WindowManager.cs:line 92 at Stylet.BootstrapperBase.DisplayRootView(Object rootViewModel) in /_/Stylet/BootstrapperBase.cs:line 100 at Stylet.Bootstrapper`1.Launch() in /_/Stylet/Bootstrapper.cs:line 92
> at Stylet.BootstrapperBase.Start(String[] args) in /_/Stylet/BootstrapperBase.cs:line 81 at Stylet.BootstrapperBase.b__9_0(Object o, StartupEventArgs e) in /_/Stylet/BootstrapperBase.cs:line 48
> at System.Windows.Application.OnStartup(StartupEventArgs e)
> at System.Windows.Application.<.ctor>b__1_0(Object unused)
> at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
> at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> [Launcher Version: 3.12.150]
> 
> 同样的问题
> 电脑有26G内存可用

可以提供更多信息吗？比如游戏版本？

**Comment by happyme531** [comment]
打开就报错...

**Comment by happyme531** [comment]
打开启动器就报错

**Comment by Goose-Bomb** [comment]
> 打开启动器就报错

你有哪些游戏版本呢，有没有安装forge或者fabric？之前有没有用过其他启动器来管理版本？我这里正常安装的话都是可以加载的，不知道是不是json的格式问题。
