### ISSUE TITLE
预览版获取Forge

### ISSUE THREAD

**Issue by 264388324** [Goose-Bomb/GBCLV3#28]
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GBCLV3.Services.Installation.ForgeInstallService.GetDownloadListAsync(String id)
   at GBCLV3.ViewModels.Tabs.ForgeInstallViewModel.OnActivate()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[Launcher Version: 3.0.9.104]

**Comment by Goose-Bomb** [comment]
当前判断 forge新老版本（1.12.2之前与之后）的方法是直接判断版本的数字号，只能用于正式版本。准备修改成根据版本 json 内的 **_minimumLauncherVersion_** 字段区分 1.12.2 前后的版本。
