### ISSUE TITLE
😅 There is such a thing...

### ISSUE THREAD

**Issue by vanja-san** [Goose-Bomb/GBCLV3#40]
### I download update through application:

```
System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at GBCLV3.Services.Download.UpdateService.Update()
   at GBCLV3.ViewModels.Windows.UpdateViewModel.Update()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[Launcher Version: 3.0.9.104]
```

**Comment by Goose-Bomb** [comment]
As I mentioned in the changelog, please manually download the latest release version and replace the old executable file. Because there's a bug in self-update in previous version and I cannot fix the old launchers which are already in your disk. 😖

**Comment by Goose-Bomb** [comment]
BTW I've tested the self-update in the current release version and it's working properly. So next time you are able to use the self-update function again. (I hope 🤣!)

**Comment by vanja-san** [comment]
Thx! 😊
