### ISSUE TITLE
Exception occurred when opening "Auxiliaries" 

### ISSUE THREAD

**Issue by KobeArthurScofield** [Goose-Bomb/GBCLV3#44]
Exception tracing information:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GBCLV3.Services.Auxiliary.ModService.Load(String path)
   at GBCLV3.Services.Auxiliary.ModService.<>c.<LoadAll>b__2_1(String path)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GBCLV3.ViewModels.Tabs.ModViewModel.<Reload>b__15_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at GBCLV3.ViewModels.Tabs.ModViewModel.Reload()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[Launcher Version: 3.0.10.133]
```

Game version 1.12.2 with Forge latest stable version in 2019. Version segregate enabled.
Mods are copied directly to the folder.
When clicking on the "Auxiliaries" button to check mods, exception occurred leaving a blank list like no mod have installed.

**Comment by KobeArthurScofield** [comment]
The problem seems relate to #42 , BOM problem. Some of the mod will crash the launcher.
