### ISSUE TITLE
安装12.2forge报错

### ISSUE THREAD

**Issue by ShengWeiJ** [Goose-Bomb/GBCLV3#53]
System.NullReferenceException: Object reference not set to an instance of an object.
   at GBCLV3.Services.Installation.ForgeInstallService.InstallOld(Forge forge)
   at GBCLV3.ViewModels.Tabs.ForgeInstallViewModel.InstallSelected(Forge forge)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[Launcher Version: 3.12.150]

**Comment by Goose-Bomb** [comment]
看上去是最近几个版本的1.12.2 forge改了格式，只能用外置安装器安装了。已经改用forge-installer了
