### ISSUE TITLE
自制的mod加进去后就出现了这样

### ISSUE THREAD

**Issue by bilibilimcxiaochen** [Goose-Bomb/GBCLV3#61]
System.NullReferenceException: Object reference not set to an instance of an object.
   at GBCLV3.Services.Auxiliary.ModService.LoadForgeMods(Stream infoStream)
   at GBCLV3.Services.Auxiliary.ModService.Load(String path)
   at GBCLV3.Services.Auxiliary.ModService.<>c.<LoadAll>b__2_1(String path)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GBCLV3.ViewModels.Tabs.ModViewModel.<Reload>b__15_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at GBCLV3.ViewModels.Tabs.ModViewModel.Reload()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[Launcher Version: 3.13.197]

**Comment by bilibilimcxiaochen** [comment]
。。。

**Comment by bilibilimcxiaochen** [comment]
![image](https://user-images.githubusercontent.com/81024156/111890539-386ca780-8a25-11eb-8bcf-3d6ad10aa537.png)
![image](https://user-images.githubusercontent.com/81024156/111890540-3a366b00-8a25-11eb-8aa5-35387af76b20.png)
哎。。。还没修复。。。作者加油啊

**Comment by Goose-Bomb** [comment]
你好，请试一下最新的版本还存在吗？如果仍然存在请把日志发布在这里，我加入了新的日志系统应该能更好地追踪 bug 的产生过程了。

**Comment by bilibilimcxiaochen** [comment]
他现在好了，非常感谢

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Goose ***@***.***>
发送时间: 2021年5月10日 1:14
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Goose-Bomb/GBCLV3] 自制的mod加进去后就出现了这样 (#61)


你好，请试一下最新的版本还存在吗？如果仍然存在请把日志发布在这里，我加入了新的日志系统应该能更好地追踪 bug 的产生过程了。

―
